### PR TITLE
Added missing dependency and updated a deprecated constructor

### PR DESCRIPTION
**Pull request by cmartinezledo**

### CODE REVIEW

**Comment by marianogoldman** [comment]
Something missed in last PR. Let's add the right Guava dependencies...

In ConnectionManagementStrategy, we have this:
```
import jersey.repackaged.com.google.common.base.Function;
import jersey.repackaged.com.google.common.collect.Lists;
```
Let's change for the right ones, without jersey.repackaged.

**Comment by cmartinezledo** [comment]
That imports are missing, because we are not using **Lists.transform()** anymore

**Comment by marianogoldman** [comment]
They're not missing Charly, they're wrong. Let's fix them. This is in ConnectionManagementStrategy class.

**Comment by marianogoldman** [comment]
+1

**Pull request merged**
